imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@EntityAppBundle/Resources/config/services.yml" }
    - { resource: "@StatBundle/Resources/config/services.yml" }

parameters:
    locale: fr

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    profiler: 
       enabled: false
       

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# Doctrine Configuration
doctrine:
    dbal:
    
            
        connections:
            # A collection of different named connections (e.g. default, conn2, etc)
            app:
         
                driver:   pdo_mysql
                dbname:   "%database_app_name%"
                host:     "%database_app_host%"
                port:     "%database_app_port%"
                user:     "%database_app_user%"
                password: "%database_app_password%"
                path:                 ~
                memory:               ~    
                charset: utf8mb4
                default_table_options:
                
                   charset: utf8mb4
                   collate: utf8mb4_unicode_ci
                
            rep:
         
                driver:   pdo_mysql
                dbname:   "%database_rep_name%"
                host:     "%database_rep_host%"
                port:     "%database_rep_port%"
                user:     "%database_rep_user%"
                password: "%database_rep_password%"
                path:                 ~
                memory:               ~
                charset: utf8mb4
                default_table_options:
                
                   charset: utf8mb4
                   collate: utf8mb4_unicode_ci                    
            
           
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        
    orm: 
        default_entity_manager: default
        entity_managers:
            default:
                connection: app
                mappings:
                    EntityAppBundle:  ~

         
            rep:
                connection: rep
                mappings:
                    EntityAppBundle: ~     


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
